---
version: '3.8'
services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - diploma_pg_15_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    image: kempasso/coursework:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
  bot:
    image: kempasso/coursework:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    command: python3 manage.py runbot

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started

volumes:
  diploma_pg_15_data: